### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jmgirard** [jmgirard/lordicon#4]
- [x] Add support for `target` argument - added in v0.5.1
- [ ] Add support for `loading` argument
- [ ] Add support for `icon` argument - low priority
